### ISSUE TITLE
[Feat] API 테스트 프로젝트 작성

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#17]
**Issue : Feature**
Namo의 API 구조 프로젝트를 작성합니다.

**Description**
Swift 5.5부터 지원하는 Async-Await를 사용하여, 별도의 Combine 작업 없이 API를 작성합니다.
 - Alamofire를 사용합니다.
 - Clean Architecture의 Data/Repository를 고려하여 작성합니다.
 - 기본적인 AuthManager - Intercepter를 작성하여 가이드를 제시합니다.
 - Moya의 구조를 채용하여 작성합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
기준 위치 경로는 /Namo_SwiftUI/Data/API 입니다.
- [x] Base/EndPoint 프로토콜 작성
- [x] Base/APITask 작성
- [x] Base/APIError 작성
- [x]  ../../Model/DTO/example/testDTO 작성
- [x] EndPoint/example/ScheduleEndPoint 작성
- [x] Base/APIManager 작성
- [x] Auth/AuthManager 작성
- [x] ../../Repository/example/Schedule/ScheduleRepository 작성
- [x] ../../Repository/example/Schedule/ScheduleRepositoryImpl 작성
- [x] ../../Common/Extension/Data+ 작성
- [x] 예시 추가

**Reference(Optional)**
투두리스트 순서대로 코드를 확인하시면 플로우가 얼추 맞을 것 같습니다
