### ISSUE TITLE
[Refactor] 인증 관련 로직 리팩토링

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#183]
**Issue : Feature**
앱 진입/재진입, API 연결 등에 사용되는 KeyChainManager를 작성합니다.
이후, 연결되는 API Manager, Auth Manager의 로직을 리팩토링합니다.

**Description**
기존에 SharedUtil 모듈에 존재하던 KeyChainManager의 로직을 리팩토링합니다.
1. 모듈 시스템에 맞추어 내부에서 발생한 에러를 throw해서, 호출하는 모듈에서 처리할 수 있게 변경합니다.
2. 키체인 로직을 보강합니다.
3. Class로 작성된 manager를 struct로 재구성합니다.
- 기존 Class로 작성된 KeyChainManager는 내부 상태를 갖지 않고, Struct 구성을 통해 static method로 접근하여 메모리적 이점을 가질 수 있어 Struct로 리팩토링합니다.

API Manager의 부분에서 KeyChainManager와 연결된 로직을 리팩토링합니다.
- 기존에 불필요하게 산재되어 있던 로직을 통합하고, 발산하는 로직들을 묶어 흐름을 일렬화 합니다.
기존 AuthManger를 Req Interceptor와 Manager로 분리하여 토큰을 포함한 유저 정보 관리 모듈을 작성합니다.
- 기존의 네이밍을 바꾸고, 역할메 맞게 재작성합니다.
- 기존 AuthUsecase의 로그아웃, 회원 탈퇴 로직을 보강합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 키체인 로직 리팩토링
- [x] KeyChainManager 변동 사항 적용
- [x] API Manager 리팩토링
- [x] Auth Manager 리팩토링
