### ISSUE TITLE
[Feat] Splash/Onboarding Coordinator 로직 작성

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#188]
**Issue : Feature**
온보딩 화면 흐름을 관리하는 
1. Splash Coordinator
2. Onboarding Coordinator 로직을 작성합니다.

**Description**
1. Splash Coordinator는 스플래시 중 앱 내 필요 체크 사항 분기처리를 담당합니다.
2. Onboarding Coordinator는 로그인 - 약관동의  - 회원정보 입력 - 확인 화면 플로우를 관리합니다.
로직은 TCA Coordinator 구조로 작성하며, AppCoordinator의 로직과 연결합니다.
필요시 AppCoordinator의 로직, FeatureOnboarding의 로직을 수정합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] AuthManager 관련 필요 사항 추가
- [x] SplashCoordinator 로직 작성
- [x] OnboardingCoordinator 로직 작성
- [x] AppCoordinaotr 로직 작성
- [x] Coordinator - View 연결

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
