### ISSUE TITLE
[Feat] 온보딩 플로우 기획 수정사항 반영

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#196]
**Issue : Feature**
온보딩 플로우에서 수정된 기획 사항을 반영합니다.

**Description**
약관 동의 화면에서 보류 중인 사항을 주석 처리,
회원 정보 입력 화면에서의 UI처리와 입력받는 정보,
회원 정보 확인 화면을 수정합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 약관 동의 화면
- [x] 회원 정보 입력 화면
- [x] 회원 정보 확인 화면

**Reference(Optional)**
-
