### ISSUE TITLE
[Feat] 클린 아키텍처 적용 및 Factory를 통한 DI 구현

### ISSUE THREAD

**Issue by letskooo** [UMC-Project-Namo/iOS_SwiftUI#20]
**Issue : Feature**
클린 아키텍처를 적용하고 Factory 라이브러리를 활용해 의존성 주입(DI)을 구현합니다.

**Description**
기존 Presentation Layer에 포함되었던 ViewModel을 사용하는 구조에서 ViewModel을 삭제하고
AppState와 Interactor를 Business Layer를 두는 클린 아키텍처 구조로 변경합니다.

Factory 라이브러리를 활용하여 의존성 주입을 구현합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 기존 ViewModel 삭제(일부 ViewModel은 추후 삭제 예정)
- [ ] AppState와 Interactor로 구성된 Business Layer 추가
- [ ] Factory 라이브러리의 Container 구성
- [ ] AppState와 Interactor, View의 참조 관계 예시 작성
