### ISSUE TITLE
[Fix] 모임일정 변경 디자인대응 및 미비사항 수정

### ISSUE THREAD

**Issue by kwon-seokki** [UMC-Project-Namo/iOS_SwiftUI#204]
**Issue : Feature**
모임일정 변경된 디자인을 대응하고 미비사항을 수정합니다.

**Description**
모임일정 변경된 디자인을 대응하고 미비사항을 수정합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 모임일정 디자인 수정
- [x] 친구 초대하기 기능 추가
- [ ] 초대한 친구 일정보기 화면 연결
- [x] 지도검색 화면연결 및 지도 표시
- [ ] ~~지도검색 Inetrface -> Source 이동(임시)~~

**Reference(Optional)**
친구 초대하기 기능 추가 -> 해당 부분은 착오가 있어서 추가적으로 구현합니다.
