### ISSUE TITLE
[Feat] 모임기록 API 연동 및 구현

### ISSUE THREAD

**Issue by kwon-seokki** [UMC-Project-Namo/iOS_SwiftUI#205]
**Issue : Feature**
모임기록 API 연동 및 구현

**Description**
모임기록 API를 연동하고 관련 기능을 구현합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 별도의 모듈로 분리
- [ ] 모임 기록/일기장
- [ ] 모임 기록/활동
- [ ] 모임 기록/삭제
- [ ] 모임 기록/편집 상세
- [ ] 모임 기록/보기 상세

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
