### ISSUE TITLE
[Feat] 소셜 로그인 구현 및 앱 실행 구조 설계

### ISSUE THREAD

**Issue by letskooo** [UMC-Project-Namo/iOS_SwiftUI#23]
**Issue : Feature**
소셜 로그인 구현 및 앱 실행 구조를 설계합니다.

**Description**
소셜 로그인을 구현하고 키체인을 적용하여 앱 실행 구조를 설계합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 키체인 매니저 구현
- [ ] 카카오 소셜 로그인 구현
- [ ] 네이버 소셜 로그인 구현
- [ ] 애플 소셜 로그인 구현
- [ ] 앱 실행 구조 설계
