### ISSUE TITLE
[Feat] 그룹 캘린더 구현

### ISSUE THREAD

**Issue by iHyunWoo** [UMC-Project-Namo/iOS_SwiftUI#29]
**Issue : Feature**
그룹 캘린더 기능 및 UI 구현

**Description**
1. GroupMainView UI 구현
2. Group Calendar 구현
3. Group 일정 조회 구현
4. Group 생성 및 참여 구현

**Todo**
- [x] GroupMainView UI 구현
- [x] Group Calendar 구현
- [x] Group 일정 조회 구현
- [x] Group 생성 및 참여 구현

**Reference**
캘린더 이후 작업에 대한 분배 논의 필요합니다.
