### ISSUE TITLE
[Feat] 기록 화면 구현

### ISSUE THREAD

**Issue by EunsuSeo01** [UMC-Project-Namo/iOS_SwiftUI#31]
**Issue : Feature**
기록 화면 구현

**Description**
1. 개인 기록 탭의 UI를 구현한다
2. 모임 기록 탭의 UI를 구현한다

**Todo**
- [x] 기록이 없을 때 화면 구현
- [x] 기록이 있을 때 화면 구현
- [x] 기록 추가 화면 구현
- [x] 개인 / 모임 탭의 기록 수정 화면 구현
- [x] 기록 삭제 화면 구현
- [x] 모임 기록 추가 및 편집 화면 구현
- [x] 모임 기록 정산 Alert 연결
- [x] 모임 기록 장소 삭제 기능 구현

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
