### ISSUE TITLE
[Feat] 기록 및 모임 기록 API 연동 작업

### ISSUE THREAD

**Issue by EunsuSeo01** [UMC-Project-Namo/iOS_SwiftUI#35]
**Issue : Feature**
기록 및 모임 기록 관련 API 연동 작업

**Description**
1. 기록 화면 API를 연동한다.
2. 모임 기록 화면 API를 연동한다.

**Todo**
- [x] 기록 조회 API 연동
- [x] 기록 추가 API 연동
- [x] 기록 수정 API 연동
- [x] 기록 삭제 API 연동
- [x] 월간 모임 메모 조회 API 연동
- [x] 모임 메모 장소 생성 API 연동
- [x] 모임 메모 장소 수정 API 연동
- [x] 모임 메모 장소 삭제 API 연동
- [x] 모임 메모 삭제 API 연동
- [x] 뷰 간 데이터 연결 작업...

**Reference(Optional)**
- https://documenter.getpostman.com/view/20799334/2s9Y5bRMdT#ace908c5-114d-4151-b2c1-e9ade0cc57d1
