### ISSUE TITLE
[Feat] ErrorHandler 유틸리티 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#40]
**Issue : Feature**
앱 전체 플로우에 적용되는 에러 핸들러를 작성합니다.

**Description**

App 전역에서 ErrorHandler 싱글톤 호출을 통해 사용하는 것이 목적입니다.

ErrorType은
1. 무시하는 Error (로깅용)
2. 재시도하는 Error
3. Alert 표시하는 Error
4. Alert 표시와 함께 화면 변경하는 Error

4가지로 분류하여 처리 예정입니다.

1. 토큰 만료 시 에러
2. API 통신 시 에러
3. UI 화면 상호작용 시 에러
4. 그 외 catch 되는 에러들

등의 에러들을 처리합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] AppError 정의
- [x] ErrorHandlingType 정의
- [x] ErrorAlertContent, localizedDescription 작성
- [x] window - rootController 코드 작성
- [x] Error Handling 코드 작성
- [x] os logger 작성

**Reference(Optional)**
필요시 커스텀 Alert 창을 표시하는 ViewModifier도 작업합니다.
