### ISSUE TITLE
[Feat] 로그인 & 온보딩 & 회원 탈퇴 마무리 구현

### ISSUE THREAD

**Issue by letskooo** [UMC-Project-Namo/iOS_SwiftUI#46]
**Issue : Feature**
[Feat] 로그인 & 온보딩 & 회원 탈퇴 마무리 구현

**Description**
로그인 및 온보딩, 회원 탈퇴 기능을 구현합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 애플 로그인 구현
- [ ] 회원 약관 API 추가 적용
- [ ] 회원 탈퇴 기능 구현
