### ISSUE TITLE
[Feat] 캘린더에 보여지는 일정 개수 초과 시 표시하는 방법 변경

### ISSUE THREAD

**Issue by iHyunWoo** [UMC-Project-Namo/iOS_SwiftUI#55]
**Issue : Feature**
캘린더에 보여지는 일정 개수 초과 시 +숫자 로 표시하도록 변경합니다.

**Description**
일정 개수 표시하는 이슈 외에 캘린더 기타 버그 수정

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [ ] 일정 개수 표시
- [ ] 일정 받아올 때 startDate순으로 정렬
- [ ] 일정 detail list에서 제목이 긴 경우 말 줄임표로 변경
