### ISSUE TITLE
[Feat] 홈 화면 QA 반영

### ISSUE THREAD

**Issue by iHyunWoo** [UMC-Project-Namo/iOS_SwiftUI#60]
**Issue : Feature**
홈 화면에서 QA 수정 사항을 반영합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 탭 바 아이콘 SVG로 변경
- [x] 캘린더 date 계산 문제 수정
- [x] 캘린더 detail 바텀 시트 띄울 때 탭 바 보이도록 변경
- [x] 홈 캘린더에서 현재 날짜 연속 클릭 시 현재 날짜가 아닌 지속적으로 스크롤 되는 문제 수정
