### ISSUE TITLE
[Feat] 그룹 QA 반영

### ISSUE THREAD

**Issue by iHyunWoo** [UMC-Project-Namo/iOS_SwiftUI#63]
**Issue : Feature**
그룹 관련 기능에서 QA 후 수정사항을 반영합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 그룹 캘린더에서 일정 추가 후 캘린더 리로드
- [x] 그룹 뒤로가기 버튼 이미지 svg로 변경
- [x] 그룹 탈퇴 후 토스트 메세지
