### ISSUE TITLE
[Feat] 기록 QA 반영

### ISSUE THREAD

**Issue by EunsuSeo01** [UMC-Project-Namo/iOS_SwiftUI#68]
**Issue : Feature**
기록 관련 기능에서 QA 후 수정사항을 반영합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 기록 헤더 높이 수정
- [x] 개인 ↔ 모임 토글 전환 바로 되도록
- [x] 기록 상세보기 화면에서 나오는 색상이 일정과 다름
- [x] 입력 후 배경 클릭 시 키보드 내리기
