### ISSUE TITLE
[Feat] 일정 QA 반영

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#69]
**Issue : Feature**
일정 관련 기능에서 QA 후 수정사항을 반영합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 모임 일정 추가 시 기본 참석자를 그룹원 전체로 설정
- [x] 일정 추가시 일정 이름 검증 추가
- [x] 모임 일정 참석자 선택 표시 문제 수정
- [x] 화면 탭하면 키보드 내려가는 기능 구현

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
