### ISSUE TITLE
[Feat] 기록 부분 남은 작업 구현

### ISSUE THREAD

**Issue by iHyunWoo** [UMC-Project-Namo/iOS_SwiftUI#77]
**Issue : Feature**
기록 탭과 관련된 남은 작업들을 구현합니다.

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 기록 토글 후 리스트 업데이트
- [x] 모임 기록에서 정산 연결
- [x] 모임 기록 활동 삭제 구현
