### ISSUE TITLE
[Feat] 개인 및 모임 기록 관련 2차 QA 반영

### ISSUE THREAD

**Issue by EunsuSeo01** [UMC-Project-Namo/iOS_SwiftUI#83]
**Issue : Feature**
개인 및 모임 기록 관련 2차 QA

**Todo**
- [x] 모임 기록 작성된 거면 수정 화면으로 넘어가야 함 -> isEditingDiary 값 업데이트해서 해결
- [x] 월간 기록 목록에서 수정으로 이동 시 이미지 데이터 연결
- [x] 기록 수정 시 이미지 데이터 연결 -> 들어는 가는데 조회 시 바로! 업데이트는 안 됨
- [x] 사진이 3개 들어갔을 경우 뷰 깨짐
- [x] 개인의 모임 기록에서는 이미지 수정 안 되도록 설정
- [x] 활동 리스트 데이터 연결
