### ISSUE TITLE
[Fix] 기록 관련 3차 QA 반영

### ISSUE THREAD

**Issue by EunsuSeo01** [UMC-Project-Namo/iOS_SwiftUI#95]
**Issue : Fix**
기록 관련 3차 QA 작업을 진행합니다.

**Todo**
- [x] 모임 기록 상세 조회 API 연동
- [x] 텍스트만 편집했을 때 사진 없어지는 에러 해결
- [x] 기록 아이템 레이아웃 및 스타일 수정
- [x] 다이어리 메인에서는 기록 내용 줄바꿈 없애고 공백으로 처리
- [x] TextEditor 200자 제한 적용
- [x] 활동 placeholder 설정
- [x] 장소 비었을 때 없음으로 설정
- [x] 다른 화면 갔다가 와도 개인 / 모임 선택된 탭 유지
- [x] 네비게이션 바 배경색 설정으로 뷰 겹치는 현상 해결
- [x] 사진 중복 에러 해결
- [x] 활동 편집 시 참가자 정보 데이터 연결
- [x] 기록 수정 화면 들어갈 때 이미지 연결 안 되는 에러 해결
- [x] activityId 0 값으로 활동 수정과 생성을 구분
- [x] 각 활동마다 images를 가지는 구조로 변경 -> 복수개의 활동에 대한 사진 추가 및 수정 가능해짐
- [x] 다이어리 탭에서만 잘 보이고 일정에서 기록으로 진입 시에는 이미지가 잘 연결 안 되는 에러가 있었으나 잘 보이도록 수정함 -> 기록 탭에서 수정한 게 일정에서 기록으로 진입 시에도 잘 보이고 그 반대도 가능!
- [x] 모임 기록 삭제 API 필드값 수정 -> 모임 기록 삭제 가능해짐
- [x] 활동별 정산 데이터 제대로 나오게 수정
- [x] 정산 인원 체크 표시 유지 안 되는 에러 해결 + 활동 여러개일 때도 각자 다르게 설정할 수 있게 수정함
- [x] 활동 이미지 이전에 조회한 활동 이미지로 나오는 에러 수정
- [x] 장소 수정, 삭제 API 필드 이름 수정
