### ISSUE TITLE
[Fix] 일정 QA 3차 반영

### ISSUE THREAD

**Issue by FpRaArNkK** [UMC-Project-Namo/iOS_SwiftUI#96]
**Description**
일정 QA를 3차로 반영합니다

**Todo**
작업해야 하는 투두리스트를 작성해주세요.
- [x] 일정의 카테고리 표시 안되는 문제 수정
- [x] 지도의 선택 표시 문제 수정
- [x] 지도 라벨 태그, 모임 지도 표시 수정
- [x] [모임 일정(개인)] 개인이 카테고리 변경
- [x] [모임 일정 편집(개인)] 개인은 카테고리와 알림만 편집
- [ ] 일정 생성에서 name 검증 (Toast)
- [x] 일정 추가/편집 화면 프로퍼티 변경시 다른 프로퍼티 표시 창 토글처리
- [x] 알림 설정 주석 처리

**Reference(Optional)**
작업에 대해 참고하거나 알아야 할 기타사항이 있다면 작성해주세요.
